---
- name: Supervisor | Install deps
  apt:
    update_cache: yes
    name: supervisor
    state: present
- name: Supervisor | Supervisor service is running
  service:
    name: supervisor
    state: started
    enabled: true
- name: Supervisor | install tasks
  template:
    src: program.ini.j2
    dest: "/etc/supervisor/conf.d/{{ item.name }}.conf"
  with_items: "{{ programs }}"
- name: Supervisor | read new entry
  command: supervisorctl reread
- name: Supervisor | update
  command: supervisorctl update