# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/php
image: oprax/debian:ansible

# https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
services:
 - ansible/ansible:ubuntu1604py3

stages:
  - build
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

ansible:
  stage: build
  before_script:
    - cp vars.test.yml vars.yml
    - cp hosts.test hosts
    - echo "password" > .vault_pass
    - ssh-keygen -t rsa -b 4096 -C "test@example.com" -N "" -f "/root/.ssh/id_rsa"
  script:
    - ansible-playbook -i hosts install.yml --vault-password-file .vault_pass


