---
- name: Server install
  hosts: web
  remote_user: "{{ remote_user }}"
  become: true
  tasks:
  - include_vars:
      file: vars.yml
  - name: "USER | Create {{ user }}"
    user:
      name: "{{ user }}"
      group: www-data
      shell: /bin/bash
  - name: "USER | SSH key ({{ user }})"
    authorized_key:
      user: "{{ user }}"
      key: "{{ lookup('file', ssh_public_key_file) }}"
      state: present
  - name: USER | SSH private key
    copy:
      src: "{{ ssh_private_key_file }}"
      dest: "/home/{{ user }}/.ssh/id_rsa"
      owner: "{{ user }}"
      mode: 0600
    when: ssh_private_key_file is defined
  - name: APT | Update
    apt:
      upgrade: dist
      update_cache: yes
  - name: ROLES | secure
    include_role:
      name: secure
  - name: ROLES | Tools
    include_role:
      name: tools
  - name: ROLES | MySQL
    when: database.driver == "mysql"
    include_role:
      name: mysql
  - name: ROLES | PgSQL
    when: database.driver == "pgsql"
    include_role:
      name: pgsql
  - name: ROLES | PHP
    when: php_version is defined
    include_role:
      name: php
  - name: ROLES | Python
    when: python_version is defined
    include_role:
      name: python
  - name: ROLES | Nginx
    include_role:
      name: nginx
  - name: ROLES | NodeJS
    include_role:
      name: nodejs
  - name: Create GIT repo
    command: "git init --bare {{ ansistrano_deploy_to }}.git"
    args:
      creates: "{{ ansistrano_deploy_to }}.git"
    become: true
    become_user: "{{ user }}"
