---
- name: NGINX | Install
  apt:
    name: nginx
    state: present
- name: "NGINX | Remove default config"
  file:
    path: "/etc/nginx/nginx.conf"
    state: absent
- name: NGINX | Default config
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
- name: NGINX | Default vhost
  template:
    src: default.j2
    dest: "/etc/nginx/sites-enabled/default"
- name: "NGINX | Pre Vhost {{ domain }}"
  template:
    src: pre-vhost.j2
    dest: "/etc/nginx/sites-enabled/{{ domain }}"
- name: "NGINX | Restart"
  service:
    name: nginx
    state: restarted
- import_tasks: letsencrypt.yml
  when: certs
- name: "NGINX | Vhost {{ domain }}"
  template:
    src: vhost.j2
    dest: "/etc/nginx/sites-enabled/{{ domain }}"
- name: "NGINX | Restart"
  service:
    name: nginx
    state: restarted