- name: LARAVEL | NPM install
  command: npm install
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
- name: LARAVEL | build assets
  command: npm run prod
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
# END.YML
- name: LARAVEL | Config cache
  shell: php artisan config:cache
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
- name: LARAVEL | View clear
  shell: php artisan view:clear
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
- name: LARAVEL | Public storage
  shell: php artisan storage:link
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
    creates: "{{ ansistrano_release_path.stdout }}/public/storage"
- name: LARAVEL | Migrate
  shell: php artisan migrate --force
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
- name: LARAVEL | Seed
  shell: php artisan db:seed --force
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
    creates: "{{ ansistrano_shared_path }}/seeded"
  when: ansistrano_shared_path is defined
- name: LARAVEL | Seeded
  file:
    path: "{{ ansistrano_shared_path }}/seeded"
    state: touch
  when: ansistrano_shared_path is defined
- name: LARAVEL | extra commands
  command: "{{ item }}"
  with_items: "{{ extra_cmd }}"
  args:
    chdir: "{{ ansistrano_deploy_to }}/current"
- name: LARAVEL | Crontab
  cron:
      name: "Laravel schedule"
      user: "{{ user }}"
      state: present
      job: "cd {{ ansistrano_deploy_to }}/current && php artisan schedule:run >> /dev/null 2>&1"
  when: laravel_schedule is defined
- name: Laravel | start
  command: "supervisorctl start {{ item.name }}:*"
  with_items: "{{ programs }}"
  remote_user: "{{ remote_user }}"
  become: true
