- name: LARAVEL | .env 1
  vars:
    app_key:
      stdout: "base64:zr7XcuNmj/tKEReLCB3yxO2c6sANBH2stIOKnmyjg7Q="
  template:
    src: env.j2
    dest: "{{ ansistrano_release_path.stdout }}/.env"
- name: LARAVEL | Composer install
  composer:
    command: install
    working_dir: "{{ ansistrano_release_path.stdout }}"
    optimize_autoloader: true
- name: LARAVEL | Clean .env
  file:
    state: absent
    path: "{{ ansistrano_release_path.stdout }}/.env"
- name: LARAVEL | App key generate
  shell: "php artisan key:generate --show > {{ ansistrano_shared_path }}/app.key"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
    creates: "{{ ansistrano_shared_path }}/app.key"
- name: LARAVEL | App key generate
  command: "cat {{ ansistrano_shared_path }}/app.key"
  register: app_key
- name: LARAVEL | .env 2
  template:
    src: env.j2
    dest: "{{ ansistrano_shared_path }}/.env"
- name: Laravel | remove cache
  remote_user: "{{ remote_user }}"
  become: true
  file:
    path: "{{ ansistrano_deploy_to }}/current/storage/framework/cache/data"
    state: absent
- name: Laravel | restore cache
  file:
    path: "{{ ansistrano_deploy_to }}/current/storage/framework/cache/data"
    owner: "{{ user }}"
    group: www-data
    state: directory
- name: LARAVEL | Storage directory
  file:
    path: "{{ item }}"
    mode: 0777
    state: directory
  with_items:
    - "{{ ansistrano_shared_path }}/storage/app/public"
    - "{{ ansistrano_shared_path }}/storage/framework/cache"
    - "{{ ansistrano_shared_path }}/storage/framework/sessions"
    - "{{ ansistrano_shared_path }}/storage/framework/testing"
    - "{{ ansistrano_shared_path }}/storage/framework/views"
    - "{{ ansistrano_shared_path }}/storage/logs"
# https://stackoverflow.com/a/37266353/10324791
- name: LARAVEL | Storage directory permissions
  shell: |
      find {{ ansistrano_deploy_to }} -type f -exec chmod 664 {} \;
      find {{ ansistrano_deploy_to }} -type d -exec chmod 775 {} \;
# - name: LARAVEL | Dir & File permission {{ ansistrano_release_path.stdout }}/storage {{ ansistrano_release_path.stdout }}/bootstrap/cache
#   shell: |
#     chgrp -R www-data {{ ansistrano_release_path.stdout }}/storage {{ ansistrano_release_path.stdout }}/bootstrap/cache
#     chmod -R ug+rwx {{ ansistrano_release_path.stdout }}/storage {{ ansistrano_release_path.stdout }}/bootstrap/cache
- name: LARAVEL | NPM install
  command: npm install
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
- name: LARAVEL | build assets
  command: npm run prod
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
- name: Laravel | status supervisor
  command: "supervisorctl status {{ item.name }}:*"
  with_items: "{{ programs }}"
  remote_user: "{{ remote_user }}"
  become: true
  register: supervisor_status
  when: programs is defined
- name: Laravel | stop supervisor
  command: php artisan horizon:terminate
  when:
   - supervisor_status is defined
   - supervisor_status.results[0].stdout.find('RUNNING') != -1
  args:
    chdir: "{{ ansistrano_deploy_to }}/current"
