- name: LARAVEL | .env 1
  vars:
    app_key:
      stdout: "base64:zr7XcuNmj/tKEReLCB3yxO2c6sANBH2stIOKnmyjg7Q="
  template:
    src: env.j2
    dest: "{{ ansistrano_release_path.stdout }}/.env"
- name: LARAVEL | Composer install
  composer:
    command: install
    working_dir: "{{ ansistrano_release_path.stdout }}"
    optimize_autoloader: true
- name: LARAVEL | Clean .env
  file:
    state: absent
    path: "{{ ansistrano_release_path.stdout }}/.env"
- name: LARAVEL | App key generate
  shell: "php artisan key:generate --show > {{ ansistrano_shared_path }}/app.key"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
    creates: "{{ ansistrano_shared_path }}/app.key"
- name: LARAVEL | App key generate
  command: "cat {{ ansistrano_shared_path }}/app.key"
  register: app_key
- name: LARAVEL | .env 2
  template:
    src: env.j2
    dest: "{{ ansistrano_shared_path }}/.env"
# https://stackoverflow.com/a/37266353/10324791
- name: LARAVEL | Storage directory
  shell: |
      find {{ ansistrano_deploy_to }} -type f -exec chmod 664 {} \;
      find {{ ansistrano_deploy_to }} -type d -exec chmod 775 {} \;
