---
- name: TOOLS | Install
  apt:
    name:
      - vim
      - git
      - tree
      - htop
      - safe-rm
      - redis-server
      - unzip
      - apt-transport-https
      - lsb-release
      - ca-certificates
      - curl
      - wget
    state: present
- name: TOOLS | vim conf
  get_url:
    url: https://github.com/Oprax/dotfiles/raw/master/.vimrc
    dest: ~/.vimrc
- name: "TOOLS | vim conf for {{ user }}"
  get_url:
    url: https://github.com/Oprax/dotfiles/raw/master/.vimrc
    dest: "/home/{{ user }}/.vimrc"
    owner: "{{ user }}"
