---
- name: MySQL | Install
  apt:
    name:
      - mysql-server
      - python-mysqldb
    state: present
- name: MySQL | Set root password
  mysql_user:
    check_implicit_admin: yes 
    login_user: root
    login_password: "{{ database.root_pswd }}"
    user: root
    host: localhost
    password: "{{ database.root_pswd }}"
- name: MySQL | Remove anonymous user
  mysql_user:
    login_user: root
    login_password: "{{ database.root_pswd }}"
    user: ""
    state: absent
- name: MySQL | Remove test database
  mysql_db:
    login_user: root
    login_password: "{{ database.root_pswd }}"
    db: test
    state: absent
- name: MySQL | Remove test database
  mysql_db:
    login_user: root
    login_password: "{{ database.root_pswd }}"
    db: test
    state: absent
- name: "MySQL | Create {{ database.name }} database"
  mysql_db:
    login_user: root
    login_password: "{{ database.root_pswd }}"
    db: "{{ database.name }}"
    state: present
- name: "MySQL | Add {{ database.user }}"
  mysql_user:
    login_user: root
    login_password: "{{ database.root_pswd }}"
    user: "{{ database.user }}"
    password: "{{ database.pswd }}"
    host: localhost
    priv: "{{ database.name }}.*:ALL"
    state: present
