---
- name: MySQL | Install
  apt:
    name:
      - mysql-server
      - python-mysqldb
    state: present
- name: MySQL | Set root password
  mysql_user:
    check_implicit_admin: yes 
    login_user: root
    login_password: "{{ db_root_pswd }}"
    user: root
    host: localhost
    password: "{{ db_root_pswd }}"
- name: MySQL | Remove anonymous user
  mysql_user:
    login_user: root
    login_password: "{{ db_root_pswd }}"
    user: ""
    state: absent
- name: MySQL | Remove test database
  mysql_db:
    login_user: root
    login_password: "{{ db_root_pswd }}"
    db: test
    state: absent
- name: MySQL | Remove test database
  mysql_db:
    login_user: root
    login_password: "{{ db_root_pswd }}"
    db: test
    state: absent
- name: "MySQL | Create {{ db_name }} database"
  mysql_db:
    login_user: root
    login_password: "{{ db_root_pswd }}"
    db: "{{ db_name }}"
    state: present
- name: "MySQL | Add {{ db_user }}"
  mysql_user:
    login_user: root
    login_password: "{{ db_root_pswd }}"
    user: "{{ db_user }}"
    password: "{{ db_pswd }}"
    host: localhost
    priv: "{{ db_name }}.*:ALL"
    state: present
