---
- name: PgSql | Install
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2
    state: present
- name: PgSql | PgSql service is running
  service: name=postgresql state=started enabled=yes
- name: "PgSql | Create {{ database.name }} database"
  become_user: postgres
  become: yes
  postgresql_db:
    db: "{{ database.name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    state: present
- name: "PgSql | Add {{ database.user }}"
  become_user: postgres
  become: yes
  postgresql_user:
    name: "{{ database.user }}"
    password: "{{ database.pswd }}"
    db: "{{ database.name }}"
    state: present
    expires: infinity
- name: "PgSql | Setup priviliges for {{ database.user }}"
  become_user: postgres
  become: yes
  postgresql_privs:
    role: "{{ database.user }}"
    db: "{{ database.name }}"
    objs: ALL_IN_SCHEMA
    privs: ALL
    state: present
- name: PgSql | Ensure user does not have unnecessary privileges
  become_user: postgres
  become: yes
  postgresql_user:
    name: "{{ database.user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present
