---
- name: Python | Install deps
  apt:
    update_cache: yes
    name:
      - build-essential
      - libreadline-dev
      - libsqlite3-dev
      - libgdbm-dev
      - libreadline6-dev
      - liblzma-dev
      - libbz2-dev
      - libncurses5-dev
      - libssl-dev
      - python3-dev
      - tk-dev
      - libffi-dev
- name: Python | Fetch & unarchive source
  unarchive:
    src: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tar.xz"
    dest: /tmp
    remote_src: true
- name: Python | Configure
  command: ./configure
  args:
    chdir: "/tmp/Python-{{ python_version }}"
- name: Python | Build
  command: make
  args:
    chdir: "/tmp/Python-{{ python_version }}"
- name: Python | Install
  command: make altinstall 
  args:
    chdir: "/tmp/Python-{{ python_version }}"
- name: Python | Upgrade PIP
  command: "python{{ python_version[0:-2] }} -m pip install -U pip"